# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.api.payment_pages_api import PaymentPagesApi


class TestPaymentPagesApi(unittest.TestCase):
    """PaymentPagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentPagesApi()

    def tearDown(self) -> None:
        pass

    def test_create_payment_page(self) -> None:
        """Test case for create_payment_page

        Create Payment Page
        """
        pass

    def test_get_payment_page(self) -> None:
        """Test case for get_payment_page

        Get Payment Page
        """
        pass


if __name__ == '__main__':
    unittest.main()
