# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.setup_intent_confirm_request import SetupIntentConfirmRequest

class TestSetupIntentConfirmRequest(unittest.TestCase):
    """SetupIntentConfirmRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetupIntentConfirmRequest:
        """Test SetupIntentConfirmRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetupIntentConfirmRequest`
        """
        model = SetupIntentConfirmRequest()
        if include_optional:
            return SetupIntentConfirmRequest(
                payment_method = '',
                payment_method_data = None,
                payment_method_options = payjpv2.models.payment_method_options.Payment Method Options(),
                return_url = '',
                use_payjp_sdk = True
            )
        else:
            return SetupIntentConfirmRequest(
        )
        """

    def testSetupIntentConfirmRequest(self):
        """Test SetupIntentConfirmRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
