# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.billing_address_collection import BillingAddressCollection

class TestBillingAddressCollection(unittest.TestCase):
    """BillingAddressCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingAddressCollection(self):
        """Test BillingAddressCollection"""
        # inst = BillingAddressCollection()

if __name__ == '__main__':
    unittest.main()
