# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_page_details_response import PaymentPageDetailsResponse

class TestPaymentPageDetailsResponse(unittest.TestCase):
    """PaymentPageDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentPageDetailsResponse:
        """Test PaymentPageDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentPageDetailsResponse`
        """
        model = PaymentPageDetailsResponse()
        if include_optional:
            return PaymentPageDetailsResponse(
                id = '',
                object = 'checkout.session',
                checkout_session = payjpv2.models.checkout_session_details_response.CheckoutSessionDetailsResponse(
                    id = '', 
                    object = 'checkout.session', 
                    livemode = True, 
                    amount_subtotal = 56, 
                    amount_total = 56, 
                    billing_address_collection = 'auto', 
                    cancel_url = '', 
                    customer = null, 
                    customer_email = '', 
                    customer_details = payjpv2.models.customer_details.Customer Details(), 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    currency = 'jpy', 
                    locale = 'auto', 
                    payment_intent = null, 
                    payment_method_collection = 'always', 
                    payment_method_types = [
                        'card'
                        ], 
                    payment_method_options = payjpv2.models.payment_method_options.payment_method_options(), 
                    setup_intent = payjpv2.models.payment_intent_data_request.PaymentIntentDataRequest(
                        capture_method = 'automatic', 
                        description = '', 
                        metadata = payjpv2.models.metadata.Metadata(), 
                        receipt_email = '', 
                        setup_future_usage = 'off_session', ), 
                    submit_type = 'auto', 
                    mode = 'payment', 
                    ui_mode = 'embedded', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    line_items = payjpv2.models.checkout_session_line_items_response.CheckoutSessionLineItemsResponse(
                        object = 'list', 
                        data = [
                            payjpv2.models.checkout_session_line_item_data_response.CheckoutSessionLineItemDataResponse(
                                object = 'line_item', 
                                id = '', 
                                amount_subtotal = 56, 
                                amount_tax = 56, 
                                amount_total = 56, 
                                description = '', 
                                price = payjpv2.models.checkout_session_line_item_price_response.CheckoutSessionLineItemPriceResponse(
                                    id = '', 
                                    object = 'price', 
                                    livemode = True, 
                                    active = True, 
                                    metadata = payjpv2.models.metadata.Metadata(), 
                                    nickname = '', 
                                    type = 'one_time', 
                                    lookup_key = '', 
                                    product = '', 
                                    unit_amount = 56, 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                                quantity = 56, )
                            ], 
                        has_more = True, 
                        url = '', ), 
                    success_url = '', 
                    url = '', )
            )
        else:
            return PaymentPageDetailsResponse(
                id = '',
                checkout_session = payjpv2.models.checkout_session_details_response.CheckoutSessionDetailsResponse(
                    id = '', 
                    object = 'checkout.session', 
                    livemode = True, 
                    amount_subtotal = 56, 
                    amount_total = 56, 
                    billing_address_collection = 'auto', 
                    cancel_url = '', 
                    customer = null, 
                    customer_email = '', 
                    customer_details = payjpv2.models.customer_details.Customer Details(), 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    currency = 'jpy', 
                    locale = 'auto', 
                    payment_intent = null, 
                    payment_method_collection = 'always', 
                    payment_method_types = [
                        'card'
                        ], 
                    payment_method_options = payjpv2.models.payment_method_options.payment_method_options(), 
                    setup_intent = payjpv2.models.payment_intent_data_request.PaymentIntentDataRequest(
                        capture_method = 'automatic', 
                        description = '', 
                        metadata = payjpv2.models.metadata.Metadata(), 
                        receipt_email = '', 
                        setup_future_usage = 'off_session', ), 
                    submit_type = 'auto', 
                    mode = 'payment', 
                    ui_mode = 'embedded', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    line_items = payjpv2.models.checkout_session_line_items_response.CheckoutSessionLineItemsResponse(
                        object = 'list', 
                        data = [
                            payjpv2.models.checkout_session_line_item_data_response.CheckoutSessionLineItemDataResponse(
                                object = 'line_item', 
                                id = '', 
                                amount_subtotal = 56, 
                                amount_tax = 56, 
                                amount_total = 56, 
                                description = '', 
                                price = payjpv2.models.checkout_session_line_item_price_response.CheckoutSessionLineItemPriceResponse(
                                    id = '', 
                                    object = 'price', 
                                    livemode = True, 
                                    active = True, 
                                    metadata = payjpv2.models.metadata.Metadata(), 
                                    nickname = '', 
                                    type = 'one_time', 
                                    lookup_key = '', 
                                    product = '', 
                                    unit_amount = 56, 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                                quantity = 56, )
                            ], 
                        has_more = True, 
                        url = '', ), 
                    success_url = '', 
                    url = '', ),
        )
        """

    def testPaymentPageDetailsResponse(self):
        """Test PaymentPageDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
