# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.checkout_session_details_response import CheckoutSessionDetailsResponse

class TestCheckoutSessionDetailsResponse(unittest.TestCase):
    """CheckoutSessionDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutSessionDetailsResponse:
        """Test CheckoutSessionDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutSessionDetailsResponse`
        """
        model = CheckoutSessionDetailsResponse()
        if include_optional:
            return CheckoutSessionDetailsResponse(
                id = '',
                object = 'checkout.session',
                livemode = True,
                amount_subtotal = 56,
                amount_total = 56,
                billing_address_collection = 'auto',
                cancel_url = '',
                customer = None,
                customer_email = '',
                customer_details = { },
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                currency = 'jpy',
                locale = 'auto',
                payment_flow = None,
                payment_method_types = [
                    'card'
                    ],
                payment_method_options = { },
                setup_flow = None,
                submit_type = 'auto',
                mode = 'payment',
                ui_mode = 'hosted',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                metadata = {
                    'key' : null
                    },
                status = 'open',
                line_items = payjpv2.models.checkout_session_line_items_response.CheckoutSessionLineItemsResponse(
                    object = 'list', 
                    data = [
                        payjpv2.models.checkout_session_line_item_data_response.CheckoutSessionLineItemDataResponse(
                            object = 'line_item', 
                            id = '', 
                            amount_subtotal = 56, 
                            amount_tax = 56, 
                            amount_total = 56, 
                            currency = 'jpy', 
                            description = '', 
                            price = payjpv2.models.price_details_response.PriceDetailsResponse(
                                id = '', 
                                object = 'price', 
                                livemode = True, 
                                active = True, 
                                metadata = {
                                    'key' : null
                                    }, 
                                nickname = '', 
                                type = 'one_time', 
                                lookup_key = '', 
                                currency = 'jpy', 
                                product = '', 
                                unit_amount = 56, 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            quantity = 56, )
                        ], 
                    has_more = True, 
                    url = '', ),
                success_url = '',
                url = ''
            )
        else:
            return CheckoutSessionDetailsResponse(
                id = '',
                livemode = True,
                amount_subtotal = 56,
                amount_total = 56,
                billing_address_collection = 'auto',
                cancel_url = '',
                customer = None,
                customer_email = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                currency = 'jpy',
                locale = 'auto',
                payment_flow = None,
                payment_method_types = [
                    'card'
                    ],
                payment_method_options = { },
                setup_flow = None,
                submit_type = 'auto',
                mode = 'payment',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                metadata = {
                    'key' : null
                    },
                success_url = '',
                url = '',
        )
        """

    def testCheckoutSessionDetailsResponse(self):
        """Test CheckoutSessionDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
