# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.setup_intent_payment_method_preference import SetupIntentPaymentMethodPreference

class TestSetupIntentPaymentMethodPreference(unittest.TestCase):
    """SetupIntentPaymentMethodPreference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetupIntentPaymentMethodPreference:
        """Test SetupIntentPaymentMethodPreference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetupIntentPaymentMethodPreference`
        """
        model = SetupIntentPaymentMethodPreference()
        if include_optional:
            return SetupIntentPaymentMethodPreference(
                setup_intent = payjpv2.models.setup_intent_response.SetupIntentResponse(
                    id = '', 
                    object = 'setup_intent', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    livemode = True, 
                    client_secret = '', 
                    customer = '', 
                    description = '', 
                    metadata = {
                        'key' : null
                        }, 
                    payment_method = '', 
                    payment_method_options = payjpv2.models.payment_method_options.payment_method_options(), 
                    payment_method_types = [
                        ''
                        ], 
                    status = 'canceled', )
            )
        else:
            return SetupIntentPaymentMethodPreference(
                setup_intent = payjpv2.models.setup_intent_response.SetupIntentResponse(
                    id = '', 
                    object = 'setup_intent', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    livemode = True, 
                    client_secret = '', 
                    customer = '', 
                    description = '', 
                    metadata = {
                        'key' : null
                        }, 
                    payment_method = '', 
                    payment_method_options = payjpv2.models.payment_method_options.payment_method_options(), 
                    payment_method_types = [
                        ''
                        ], 
                    status = 'canceled', ),
        )
        """

    def testSetupIntentPaymentMethodPreference(self):
        """Test SetupIntentPaymentMethodPreference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
