# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.api.payment_intents_api import PaymentIntentsApi


class TestPaymentIntentsApi(unittest.TestCase):
    """PaymentIntentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentIntentsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_payment_intent(self) -> None:
        """Test case for cancel_payment_intent

        Cancel Payment Intent
        """
        pass

    def test_capture_payment_intent(self) -> None:
        """Test case for capture_payment_intent

        Capture Payment Intent
        """
        pass

    def test_confirm_payment_intent(self) -> None:
        """Test case for confirm_payment_intent

        Confirm Payment Intent
        """
        pass

    def test_create_payment_intent(self) -> None:
        """Test case for create_payment_intent

        Create Payment Intent
        """
        pass

    def test_get_all_payment_intent(self) -> None:
        """Test case for get_all_payment_intent

        Get All Payment Intent
        """
        pass

    def test_increment_authorization_payment_intent(self) -> None:
        """Test case for increment_authorization_payment_intent

        Increment Authorization Payment Intent
        """
        pass

    def test_retrieve_payment_intent(self) -> None:
        """Test case for retrieve_payment_intent

        Retrieve Payment Intent
        """
        pass

    def test_update_payment_intent(self) -> None:
        """Test case for update_payment_intent

        Update Payment Intent
        """
        pass


if __name__ == '__main__':
    unittest.main()
