# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.checkout_session_line_items_response import CheckoutSessionLineItemsResponse

class TestCheckoutSessionLineItemsResponse(unittest.TestCase):
    """CheckoutSessionLineItemsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutSessionLineItemsResponse:
        """Test CheckoutSessionLineItemsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutSessionLineItemsResponse`
        """
        model = CheckoutSessionLineItemsResponse()
        if include_optional:
            return CheckoutSessionLineItemsResponse(
                object = 'list',
                data = [
                    payjpv2.models.checkout_session_line_item_data_response.CheckoutSessionLineItemDataResponse(
                        object = 'line_item', 
                        id = '', 
                        amount_subtotal = 56, 
                        amount_tax = 56, 
                        amount_total = 56, 
                        currency = 'jpy', 
                        description = '', 
                        price = payjpv2.models.checkout_session_line_item_price_response.CheckoutSessionLineItemPriceResponse(
                            id = '', 
                            object = 'price', 
                            livemode = True, 
                            active = True, 
                            metadata = payjpv2.models.metadata.Metadata(), 
                            nickname = '', 
                            type = 'one_time', 
                            lookup_key = '', 
                            product = '', 
                            unit_amount = 56, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        quantity = 56, )
                    ],
                has_more = True,
                url = ''
            )
        else:
            return CheckoutSessionLineItemsResponse(
        )
        """

    def testCheckoutSessionLineItemsResponse(self):
        """Test CheckoutSessionLineItemsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
