# coding: utf-8

"""
    PAY.JP API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.tax_rate_details_response import TaxRateDetailsResponse

class TestTaxRateDetailsResponse(unittest.TestCase):
    """TaxRateDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxRateDetailsResponse:
        """Test TaxRateDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxRateDetailsResponse`
        """
        model = TaxRateDetailsResponse()
        if include_optional:
            return TaxRateDetailsResponse(
                object = 'tax_rate',
                id = '',
                livemode = True,
                display_name = '',
                inclusive = True,
                percentage = 1.337,
                active = True,
                country = 'JP',
                description = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                metadata = {
                    'key' : null
                    }
            )
        else:
            return TaxRateDetailsResponse(
                id = '',
                livemode = True,
                display_name = '',
                inclusive = True,
                percentage = 1.337,
                active = True,
                country = 'JP',
                description = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                metadata = {
                    'key' : null
                    },
        )
        """

    def testTaxRateDetailsResponse(self):
        """Test TaxRateDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
