# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.statement_item_response import StatementItemResponse

class TestStatementItemResponse(unittest.TestCase):
    """StatementItemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatementItemResponse:
        """Test StatementItemResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatementItemResponse`
        """
        model = StatementItemResponse()
        if include_optional:
            return StatementItemResponse(
                subject = '売上',
                name = '',
                amount = 56,
                tax_rate = ''
            )
        else:
            return StatementItemResponse(
                subject = '売上',
                name = '',
                amount = 56,
                tax_rate = '',
        )
        """

    def testStatementItemResponse(self):
        """Test StatementItemResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
