# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_method_types import PaymentMethodTypes

class TestPaymentMethodTypes(unittest.TestCase):
    """PaymentMethodTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentMethodTypes(self):
        """Test PaymentMethodTypes"""
        # inst = PaymentMethodTypes()

if __name__ == '__main__':
    unittest.main()
