# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_intent_status import PaymentIntentStatus

class TestPaymentIntentStatus(unittest.TestCase):
    """PaymentIntentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentIntentStatus(self):
        """Test PaymentIntentStatus"""
        # inst = PaymentIntentStatus()

if __name__ == '__main__':
    unittest.main()
