# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.elements_sessions_response import ElementsSessionsResponse

class TestElementsSessionsResponse(unittest.TestCase):
    """ElementsSessionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ElementsSessionsResponse:
        """Test ElementsSessionsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ElementsSessionsResponse`
        """
        model = ElementsSessionsResponse()
        if include_optional:
            return ElementsSessionsResponse(
                payment_method_preference = None
            )
        else:
            return ElementsSessionsResponse(
                payment_method_preference = None,
        )
        """

    def testElementsSessionsResponse(self):
        """Test ElementsSessionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
