# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_intent_confirm_request import PaymentIntentConfirmRequest

class TestPaymentIntentConfirmRequest(unittest.TestCase):
    """PaymentIntentConfirmRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentIntentConfirmRequest:
        """Test PaymentIntentConfirmRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentIntentConfirmRequest`
        """
        model = PaymentIntentConfirmRequest()
        if include_optional:
            return PaymentIntentConfirmRequest(
                payment_method = '',
                receipt_email = '',
                capture_method = 'automatic',
                payment_method_data = None,
                payment_method_options = payjpv2.models.payment_method_options.Payment Method Options(),
                payment_method_types = [
                    'card'
                    ],
                return_url = '',
                use_payjp_sdk = True
            )
        else:
            return PaymentIntentConfirmRequest(
        )
        """

    def testPaymentIntentConfirmRequest(self):
        """Test PaymentIntentConfirmRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
