# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_flow_data_request_input import PaymentFlowDataRequestInput

class TestPaymentFlowDataRequestInput(unittest.TestCase):
    """PaymentFlowDataRequestInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentFlowDataRequestInput:
        """Test PaymentFlowDataRequestInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentFlowDataRequestInput`
        """
        model = PaymentFlowDataRequestInput()
        if include_optional:
            return PaymentFlowDataRequestInput(
                capture_method = 'automatic',
                metadata = {
                    'key' : null
                    },
                setup_future_usage = 'off_session'
            )
        else:
            return PaymentFlowDataRequestInput(
        )
        """

    def testPaymentFlowDataRequestInput(self):
        """Test PaymentFlowDataRequestInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
