# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_method_collection import PaymentMethodCollection

class TestPaymentMethodCollection(unittest.TestCase):
    """PaymentMethodCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentMethodCollection(self):
        """Test PaymentMethodCollection"""
        # inst = PaymentMethodCollection()

if __name__ == '__main__':
    unittest.main()
