# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_method_bank_transfer_response import PaymentMethodBankTransferResponse

class TestPaymentMethodBankTransferResponse(unittest.TestCase):
    """PaymentMethodBankTransferResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMethodBankTransferResponse:
        """Test PaymentMethodBankTransferResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentMethodBankTransferResponse`
        """
        model = PaymentMethodBankTransferResponse()
        if include_optional:
            return PaymentMethodBankTransferResponse(
                object = 'payment_method',
                id = '',
                type = 'bank_transfer',
                livemode = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                bank_transfer = payjpv2.models.bank_transfer.Bank Transfer()
            )
        else:
            return PaymentMethodBankTransferResponse(
                id = '',
                type = 'bank_transfer',
                livemode = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                bank_transfer = payjpv2.models.bank_transfer.Bank Transfer(),
        )
        """

    def testPaymentMethodBankTransferResponse(self):
        """Test PaymentMethodBankTransferResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
