# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.balance_list_response import BalanceListResponse

class TestBalanceListResponse(unittest.TestCase):
    """BalanceListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BalanceListResponse:
        """Test BalanceListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BalanceListResponse`
        """
        model = BalanceListResponse()
        if include_optional:
            return BalanceListResponse(
                object = 'list',
                url = '',
                has_more = True,
                data = [
                    payjpv2.models.balance_response.BalanceResponse(
                        object = 'balance', 
                        id = '', 
                        livemode = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        state = '集計中', 
                        statements = [
                            payjpv2.models.statement_response.StatementResponse(
                                object = 'statement', 
                                id = '', 
                                livemode = True, 
                                title = '', 
                                type = 'sales', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                term = payjpv2.models.term_response.TermResponse(
                                    id = '', 
                                    object = 'term', 
                                    livemode = True, 
                                    start_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    end_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    closed = True, ), 
                                balance = '', 
                                items = [
                                    payjpv2.models.statement_item_response.StatementItemResponse(
                                        subject = '売上', 
                                        name = '', 
                                        amount = 56, 
                                        tax_rate = '', )
                                    ], 
                                net = 56, )
                            ], 
                        closed = True, 
                        closed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        net = 56, 
                        bank_info = payjpv2.models.bank_info_response.BankInfoResponse(
                            bank_code = '', 
                            bank_branch_code = '', 
                            bank_account_type = '', 
                            bank_account_number = '', 
                            bank_account_holder_name = '', 
                            bank_account_status = '', ), )
                    ]
            )
        else:
            return BalanceListResponse(
                url = '',
                has_more = True,
                data = [
                    payjpv2.models.balance_response.BalanceResponse(
                        object = 'balance', 
                        id = '', 
                        livemode = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        state = '集計中', 
                        statements = [
                            payjpv2.models.statement_response.StatementResponse(
                                object = 'statement', 
                                id = '', 
                                livemode = True, 
                                title = '', 
                                type = 'sales', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                term = payjpv2.models.term_response.TermResponse(
                                    id = '', 
                                    object = 'term', 
                                    livemode = True, 
                                    start_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    end_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    closed = True, ), 
                                balance = '', 
                                items = [
                                    payjpv2.models.statement_item_response.StatementItemResponse(
                                        subject = '売上', 
                                        name = '', 
                                        amount = 56, 
                                        tax_rate = '', )
                                    ], 
                                net = 56, )
                            ], 
                        closed = True, 
                        closed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        net = 56, 
                        bank_info = payjpv2.models.bank_info_response.BankInfoResponse(
                            bank_code = '', 
                            bank_branch_code = '', 
                            bank_account_type = '', 
                            bank_account_number = '', 
                            bank_account_holder_name = '', 
                            bank_account_status = '', ), )
                    ],
        )
        """

    def testBalanceListResponse(self):
        """Test BalanceListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
