# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_intent_increment_authorization_request import PaymentIntentIncrementAuthorizationRequest

class TestPaymentIntentIncrementAuthorizationRequest(unittest.TestCase):
    """PaymentIntentIncrementAuthorizationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentIntentIncrementAuthorizationRequest:
        """Test PaymentIntentIncrementAuthorizationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentIntentIncrementAuthorizationRequest`
        """
        model = PaymentIntentIncrementAuthorizationRequest()
        if include_optional:
            return PaymentIntentIncrementAuthorizationRequest(
                amount = 56,
                description = ''
            )
        else:
            return PaymentIntentIncrementAuthorizationRequest(
                amount = 56,
        )
        """

    def testPaymentIntentIncrementAuthorizationRequest(self):
        """Test PaymentIntentIncrementAuthorizationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
