# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_flow import PaymentFlow

class TestPaymentFlow(unittest.TestCase):
    """PaymentFlow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentFlow:
        """Test PaymentFlow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentFlow`
        """
        model = PaymentFlow()
        if include_optional:
            return PaymentFlow(
                id = '',
                object = 'payment_flow',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                livemode = True,
                amount = 56,
                amount_capturable = 56,
                amount_received = 56,
                client_secret = '',
                customer = '',
                description = '',
                metadata = {
                    'key' : null
                    },
                payment_method = '',
                payment_method_options = { },
                payment_method_types = [
                    ''
                    ],
                status = 'canceled',
                next_action = { },
                return_url = '',
                capture_method = 'automatic',
                last_payment_error = { }
            )
        else:
            return PaymentFlow(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                livemode = True,
                amount = 56,
                amount_capturable = 56,
                amount_received = 56,
                client_secret = '',
                customer = '',
                description = '',
                metadata = {
                    'key' : null
                    },
                payment_method = '',
                payment_method_options = { },
                payment_method_types = [
                    ''
                    ],
                status = 'canceled',
                next_action = { },
                return_url = '',
                capture_method = 'automatic',
                last_payment_error = { },
        )
        """

    def testPaymentFlow(self):
        """Test PaymentFlow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
