# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.api.elements_api import ElementsApi


class TestElementsApi(unittest.TestCase):
    """ElementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ElementsApi()

    def tearDown(self) -> None:
        pass

    def test_get_elements_sessions(self) -> None:
        """Test case for get_elements_sessions

        Get Elements Sessions
        """
        pass


if __name__ == '__main__':
    unittest.main()
