# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.payment_method_options_card_request import PaymentMethodOptionsCardRequest

class TestPaymentMethodOptionsCardRequest(unittest.TestCase):
    """PaymentMethodOptionsCardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMethodOptionsCardRequest:
        """Test PaymentMethodOptionsCardRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentMethodOptionsCardRequest`
        """
        model = PaymentMethodOptionsCardRequest()
        if include_optional:
            return PaymentMethodOptionsCardRequest(
                request_extended_authorization = 'if_available',
                request_three_d_secure = 'any'
            )
        else:
            return PaymentMethodOptionsCardRequest(
        )
        """

    def testPaymentMethodOptionsCardRequest(self):
        """Test PaymentMethodOptionsCardRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
