# coding: utf-8

"""
    PAY.JP API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.apple_pay_config_request import ApplePayConfigRequest

class TestApplePayConfigRequest(unittest.TestCase):
    """ApplePayConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplePayConfigRequest:
        """Test ApplePayConfigRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplePayConfigRequest`
        """
        model = ApplePayConfigRequest()
        if include_optional:
            return ApplePayConfigRequest(
                display_preference = payjpv2.models.display_preference_request.DisplayPreferenceRequest(
                    preference = 'none', )
            )
        else:
            return ApplePayConfigRequest(
        )
        """

    def testApplePayConfigRequest(self):
        """Test ApplePayConfigRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
