# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payjpv2.models.refund_response import RefundResponse

class TestRefundResponse(unittest.TestCase):
    """RefundResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundResponse:
        """Test RefundResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundResponse`
        """
        model = RefundResponse()
        if include_optional:
            return RefundResponse(
                id = '',
                object = 'refund',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                livemode = True,
                amount = 56,
                metadata = {
                    'key' : null
                    },
                status = 'succeeded',
                payment_intent = '',
                reason = 'duplicate'
            )
        else:
            return RefundResponse(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                livemode = True,
                amount = 56,
                status = 'succeeded',
                payment_intent = '',
                reason = 'duplicate',
        )
        """

    def testRefundResponse(self):
        """Test RefundResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
