# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BillingAddressCollection(str, Enum):
    """
    BillingAddressCollection
    """

    """
    allowed enum values
    """
    AUTO = 'auto'
    REQUIRED = 'required'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BillingAddressCollection from a JSON string"""
        return cls(json.loads(json_str))


