# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from payjpv2.models.currency import Currency
from payjpv2.models.metadata_value import MetadataValue
from payjpv2.models.price_type import PriceType
from typing import Optional, Set
from typing_extensions import Self

class CheckoutSessionLineItemPriceResponse(BaseModel):
    """
    CheckoutSessionLineItemPriceResponse
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="料金ID")
    object: Optional[StrictStr] = 'price'
    livemode: Optional[StrictBool] = Field(default=None, description="本番環境かどうか")
    active: Optional[StrictBool] = Field(default=None, description="有効かどうか")
    metadata: Optional[Dict[str, MetadataValue]] = Field(default=None, description="メタデータ")
    nickname: Optional[StrictStr] = None
    type: Optional[PriceType] = Field(default=None, description="料金の種類")
    lookup_key: Optional[StrictStr] = None
    currency: Optional[Currency] = Field(default=None, description="通貨")
    product: Optional[StrictStr] = Field(default=None, description="商品ID")
    unit_amount: Optional[StrictInt] = Field(default=None, description="単価")
    created_at: Optional[datetime] = Field(default=None, description="作成日時 (UTC, ISO 8601 形式)")
    updated_at: Optional[datetime] = Field(default=None, description="更新日時 (UTC, ISO 8601 形式)")
    __properties: ClassVar[List[str]] = ["id", "object", "livemode", "active", "metadata", "nickname", "type", "lookup_key", "currency", "product", "unit_amount", "created_at", "updated_at"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['price']):
            raise ValueError("must be one of enum values ('price')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckoutSessionLineItemPriceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in metadata (dict)
        _field_dict = {}
        if self.metadata:
            for _key_metadata in self.metadata:
                if self.metadata[_key_metadata]:
                    _field_dict[_key_metadata] = self.metadata[_key_metadata].to_dict()
            _dict['metadata'] = _field_dict
        # set to None if nickname (nullable) is None
        # and model_fields_set contains the field
        if self.nickname is None and "nickname" in self.model_fields_set:
            _dict['nickname'] = None

        # set to None if lookup_key (nullable) is None
        # and model_fields_set contains the field
        if self.lookup_key is None and "lookup_key" in self.model_fields_set:
            _dict['lookup_key'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckoutSessionLineItemPriceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object") if obj.get("object") is not None else 'price',
            "livemode": obj.get("livemode"),
            "active": obj.get("active"),
            "metadata": dict(
                (_k, MetadataValue.from_dict(_v))
                for _k, _v in obj["metadata"].items()
            )
            if obj.get("metadata") is not None
            else None,
            "nickname": obj.get("nickname"),
            "type": obj.get("type"),
            "lookup_key": obj.get("lookup_key"),
            "currency": obj.get("currency"),
            "product": obj.get("product"),
            "unit_amount": obj.get("unit_amount"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


