# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from payjpv2.models.billing_address_collection import BillingAddressCollection
from payjpv2.models.checkout_session_line_items_response import CheckoutSessionLineItemsResponse
from payjpv2.models.checkout_session_mode import CheckoutSessionMode
from payjpv2.models.checkout_session_submit_type import CheckoutSessionSubmitType
from payjpv2.models.checkout_session_ui_mode import CheckoutSessionUIMode
from payjpv2.models.currency import Currency
from payjpv2.models.customer import Customer
from payjpv2.models.locale import Locale
from payjpv2.models.payment_intent import PaymentIntent
from payjpv2.models.payment_intent_data_request import PaymentIntentDataRequest
from payjpv2.models.payment_method_types import PaymentMethodTypes
from typing import Optional, Set
from typing_extensions import Self

class CheckoutSessionDetailsResponse(BaseModel):
    """
    CheckoutSessionDetailsResponse
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="ID")
    object: Optional[StrictStr] = 'checkout.session'
    livemode: Optional[StrictBool] = Field(default=None, description="本番環境かどうか")
    amount_subtotal: Optional[StrictInt] = None
    amount_total: Optional[StrictInt] = None
    billing_address_collection: Optional[BillingAddressCollection] = None
    cancel_url: Optional[StrictStr] = None
    customer: Optional[Customer] = None
    customer_email: Optional[StrictStr] = None
    customer_details: Optional[Dict[str, Any]] = Field(default=None, description="`expand` パラメーターを指定した場合、顧客の詳細情報を含んだオブジェクトが返却されます。  | 説明 | |:---| | **email**: 顧客のメールアドレス | ")
    expires_at: Optional[datetime] = None
    currency: Optional[Currency] = Field(default=None, description="価格の通貨。現在は `jpy` のみサポートしています。")
    locale: Optional[Locale] = None
    payment_intent: Optional[PaymentIntent] = None
    payment_method_types: Optional[List[PaymentMethodTypes]] = None
    payment_method_options: Optional[Dict[str, Any]] = None
    setup_intent: Optional[PaymentIntentDataRequest] = None
    submit_type: Optional[CheckoutSessionSubmitType] = None
    mode: Optional[CheckoutSessionMode] = Field(default=None, description="Checkout Session のモード  | 指定できる値 | |:---| | **hosted**: PAY.JPでホスティングしている画面を使用します。 | ")
    ui_mode: Optional[CheckoutSessionUIMode] = Field(default=None, description="Checkout Session の UI モード。デフォルトは `hosted` です。<br>  | 指定できる値 | |:---| | **hosted**: PAY.JPでホスティングしている画面を使用します。 | ")
    created_at: Optional[datetime] = Field(default=None, description="作成日時 (UTC, ISO 8601 形式)")
    updated_at: Optional[datetime] = Field(default=None, description="更新日時 (UTC, ISO 8601 形式)")
    line_items: Optional[CheckoutSessionLineItemsResponse] = None
    success_url: Optional[StrictStr] = None
    url: Optional[StrictStr] = Field(default=None, description="URL")
    __properties: ClassVar[List[str]] = ["id", "object", "livemode", "amount_subtotal", "amount_total", "billing_address_collection", "cancel_url", "customer", "customer_email", "customer_details", "expires_at", "currency", "locale", "payment_intent", "payment_method_types", "payment_method_options", "setup_intent", "submit_type", "mode", "ui_mode", "created_at", "updated_at", "line_items", "success_url", "url"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['checkout.session']):
            raise ValueError("must be one of enum values ('checkout.session')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckoutSessionDetailsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_intent
        if self.payment_intent:
            _dict['payment_intent'] = self.payment_intent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of setup_intent
        if self.setup_intent:
            _dict['setup_intent'] = self.setup_intent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of line_items
        if self.line_items:
            _dict['line_items'] = self.line_items.to_dict()
        # set to None if amount_subtotal (nullable) is None
        # and model_fields_set contains the field
        if self.amount_subtotal is None and "amount_subtotal" in self.model_fields_set:
            _dict['amount_subtotal'] = None

        # set to None if amount_total (nullable) is None
        # and model_fields_set contains the field
        if self.amount_total is None and "amount_total" in self.model_fields_set:
            _dict['amount_total'] = None

        # set to None if billing_address_collection (nullable) is None
        # and model_fields_set contains the field
        if self.billing_address_collection is None and "billing_address_collection" in self.model_fields_set:
            _dict['billing_address_collection'] = None

        # set to None if cancel_url (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_url is None and "cancel_url" in self.model_fields_set:
            _dict['cancel_url'] = None

        # set to None if customer (nullable) is None
        # and model_fields_set contains the field
        if self.customer is None and "customer" in self.model_fields_set:
            _dict['customer'] = None

        # set to None if customer_email (nullable) is None
        # and model_fields_set contains the field
        if self.customer_email is None and "customer_email" in self.model_fields_set:
            _dict['customer_email'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if locale (nullable) is None
        # and model_fields_set contains the field
        if self.locale is None and "locale" in self.model_fields_set:
            _dict['locale'] = None

        # set to None if payment_intent (nullable) is None
        # and model_fields_set contains the field
        if self.payment_intent is None and "payment_intent" in self.model_fields_set:
            _dict['payment_intent'] = None

        # set to None if payment_method_types (nullable) is None
        # and model_fields_set contains the field
        if self.payment_method_types is None and "payment_method_types" in self.model_fields_set:
            _dict['payment_method_types'] = None

        # set to None if payment_method_options (nullable) is None
        # and model_fields_set contains the field
        if self.payment_method_options is None and "payment_method_options" in self.model_fields_set:
            _dict['payment_method_options'] = None

        # set to None if setup_intent (nullable) is None
        # and model_fields_set contains the field
        if self.setup_intent is None and "setup_intent" in self.model_fields_set:
            _dict['setup_intent'] = None

        # set to None if submit_type (nullable) is None
        # and model_fields_set contains the field
        if self.submit_type is None and "submit_type" in self.model_fields_set:
            _dict['submit_type'] = None

        # set to None if line_items (nullable) is None
        # and model_fields_set contains the field
        if self.line_items is None and "line_items" in self.model_fields_set:
            _dict['line_items'] = None

        # set to None if success_url (nullable) is None
        # and model_fields_set contains the field
        if self.success_url is None and "success_url" in self.model_fields_set:
            _dict['success_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckoutSessionDetailsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object") if obj.get("object") is not None else 'checkout.session',
            "livemode": obj.get("livemode"),
            "amount_subtotal": obj.get("amount_subtotal"),
            "amount_total": obj.get("amount_total"),
            "billing_address_collection": obj.get("billing_address_collection"),
            "cancel_url": obj.get("cancel_url"),
            "customer": Customer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "customer_email": obj.get("customer_email"),
            "customer_details": obj.get("customer_details"),
            "expires_at": obj.get("expires_at"),
            "currency": obj.get("currency"),
            "locale": obj.get("locale"),
            "payment_intent": PaymentIntent.from_dict(obj["payment_intent"]) if obj.get("payment_intent") is not None else None,
            "payment_method_types": obj.get("payment_method_types"),
            "payment_method_options": obj.get("payment_method_options"),
            "setup_intent": PaymentIntentDataRequest.from_dict(obj["setup_intent"]) if obj.get("setup_intent") is not None else None,
            "submit_type": obj.get("submit_type"),
            "mode": obj.get("mode"),
            "ui_mode": obj.get("ui_mode"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "line_items": CheckoutSessionLineItemsResponse.from_dict(obj["line_items"]) if obj.get("line_items") is not None else None,
            "success_url": obj.get("success_url"),
            "url": obj.get("url")
        })
        return _obj


