# coding: utf-8

"""
    PAY.JP API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from payjpv2.models.price_data_request import PriceDataRequest
from typing import Optional, Set
from typing_extensions import Self

class LineItemRequest(BaseModel):
    """
    LineItemRequest
    """ # noqa: E501
    price_id: Optional[StrictStr] = None
    price_data: Optional[PriceDataRequest] = None
    quantity: StrictInt = Field(description="購入する商品の数量")
    tax_rates: Optional[Annotated[List[StrictStr], Field(max_length=1)]] = Field(default=None, description="税率 ID")
    __properties: ClassVar[List[str]] = ["price_id", "price_data", "quantity", "tax_rates"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.model_dump(by_alias=True, exclude_unset=True))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LineItemRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of price_data
        if self.price_data:
            _dict['price_data'] = self.price_data.to_dict()
        # set to None if price_id (nullable) is None
        # and model_fields_set contains the field
        if self.price_id is None and "price_id" in self.model_fields_set:
            _dict['price_id'] = None

        # set to None if price_data (nullable) is None
        # and model_fields_set contains the field
        if self.price_data is None and "price_data" in self.model_fields_set:
            _dict['price_data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LineItemRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "price_id": obj.get("price_id"),
            "price_data": PriceDataRequest.from_dict(obj["price_data"]) if obj.get("price_data") is not None else None,
            "quantity": obj.get("quantity"),
            "tax_rates": obj.get("tax_rates")
        })
        return _obj


