# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaymentMethodOptionsCardRequest(BaseModel):
    """
    PaymentMethodOptionsCardRequest
    """ # noqa: E501
    request_extended_authorization: Optional[StrictStr] = Field(default=None, description="オーソリ期間の延長要求。  | 指定できる値 | |:---| | **if_available**: オーソリ期間の延長が可能な場合に延長要求を行います。 | | **never**: オーソリ期間の延長要求を行いません。 |")
    request_three_d_secure: Optional[StrictStr] = Field(default=None, description="3Dセキュア認証の要求方法。  | 指定できる値 | |:---| | **any**: 基本的に3Dセキュア認証を要求します。 | | **automatic**: 必要な場合にのみ3Dセキュア認証を要求します。 | <!-- | **challenge**: 3Dセキュア認証を手動で要求します。 | --> ")
    setup_future_usage: Optional[StrictStr] = Field(default=None, description="セットアップ後の使用方法。  | 指定できる値 | |:---| | **off_session**: 顧客がその場にいない状態（例：定期課金や後日請求など）でも決済したい場合に使用します。事前の同意に基づいて自動的に課金されます。 | | **on_session**: 顧客が支払い操作中（例：Web画面で「支払う」ボタンを押す）でのみ決済できればいい場合に指定します。リアルタイムに同意が得られている状態です。 |")
    __properties: ClassVar[List[str]] = ["request_extended_authorization", "request_three_d_secure", "setup_future_usage"]

    @field_validator('request_extended_authorization')
    def request_extended_authorization_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['if_available', 'never']):
            raise ValueError("must be one of enum values ('if_available', 'never')")
        return value

    @field_validator('request_three_d_secure')
    def request_three_d_secure_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'automatic', 'challenge']):
            raise ValueError("must be one of enum values ('any', 'automatic', 'challenge')")
        return value

    @field_validator('setup_future_usage')
    def setup_future_usage_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['off_session', 'on_session']):
            raise ValueError("must be one of enum values ('off_session', 'on_session')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentMethodOptionsCardRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentMethodOptionsCardRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "request_extended_authorization": obj.get("request_extended_authorization"),
            "request_three_d_secure": obj.get("request_three_d_secure"),
            "setup_future_usage": obj.get("setup_future_usage")
        })
        return _obj


