# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PlanCreateRequest(BaseModel):
    """
    PlanCreateRequest
    """ # noqa: E501
    amount: Annotated[int, Field(le=9999999, strict=True, ge=50)] = Field(description="必須。50~9,999,999の整数")
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(description="必須。3文字のISOコード(現状 'jpy' のみサポート)")
    interval: StrictStr = Field(description="必須。月次課金であれば'month'を、年次課金であれば'year'を指定")
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    trial_days: Optional[StrictInt] = None
    billing_day: Optional[Annotated[int, Field(le=31, strict=True, ge=1)]] = None
    metadata: Optional[Dict[str, StrictStr]] = None
    __properties: ClassVar[List[str]] = ["amount", "currency", "interval", "id", "name", "trial_days", "billing_day", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlanCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if trial_days (nullable) is None
        # and model_fields_set contains the field
        if self.trial_days is None and "trial_days" in self.model_fields_set:
            _dict['trial_days'] = None

        # set to None if billing_day (nullable) is None
        # and model_fields_set contains the field
        if self.billing_day is None and "billing_day" in self.model_fields_set:
            _dict['billing_day'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlanCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "interval": obj.get("interval"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "trial_days": obj.get("trial_days"),
            "billing_day": obj.get("billing_day"),
            "metadata": obj.get("metadata")
        })
        return _obj


