# coding: utf-8

"""
    PAY.JP API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from payjpv2.models.currency import Currency
from payjpv2.models.product_data_request import ProductDataRequest
from typing import Optional, Set
from typing_extensions import Self

class PriceDataRequest(BaseModel):
    """
    PriceDataRequest
    """ # noqa: E501
    currency: Currency = Field(description="通貨。現在は `jpy` のみサポートしています。")
    unit_amount: Annotated[int, Field(strict=True, ge=0)] = Field(description="単価（0以上の整数）")
    product_id: Optional[StrictStr] = None
    product_data: Optional[ProductDataRequest] = None
    __properties: ClassVar[List[str]] = ["currency", "unit_amount", "product_id", "product_data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.model_dump(by_alias=True, exclude_unset=True))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PriceDataRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of product_data
        if self.product_data:
            _dict['product_data'] = self.product_data.to_dict()
        # set to None if product_id (nullable) is None
        # and model_fields_set contains the field
        if self.product_id is None and "product_id" in self.model_fields_set:
            _dict['product_id'] = None

        # set to None if product_data (nullable) is None
        # and model_fields_set contains the field
        if self.product_data is None and "product_data" in self.model_fields_set:
            _dict['product_data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PriceDataRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "unit_amount": obj.get("unit_amount"),
            "product_id": obj.get("product_id"),
            "product_data": ProductDataRequest.from_dict(obj["product_data"]) if obj.get("product_data") is not None else None
        })
        return _obj


