# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from payjpv2.models.payment_method_create_request import PaymentMethodCreateRequest
from typing import Optional, Set
from typing_extensions import Self

class SetupIntentConfirmRequest(BaseModel):
    """
    SetupIntentConfirmRequest
    """ # noqa: E501
    payment_method: Optional[StrictStr] = Field(default=None, description="この SetupIntent に紐付ける決済方法のID")
    payment_method_data: Optional[PaymentMethodCreateRequest] = Field(default=None, description="支払い方法データ")
    payment_method_options: Optional[Dict[str, Any]] = Field(default=None, description="この SetupIntent の支払い方法の個別設定。")
    return_url: Optional[StrictStr] = Field(default=None, description="顧客が支払いを完了後、あるいはキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。`confirm=true` の場合のみ指定できます。")
    use_payjp_sdk: Optional[StrictBool] = Field(default=None, description="PAY.JP SDK を使用するかどうか")
    __properties: ClassVar[List[str]] = ["payment_method", "payment_method_data", "payment_method_options", "return_url", "use_payjp_sdk"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetupIntentConfirmRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of payment_method_data
        if self.payment_method_data:
            _dict['payment_method_data'] = self.payment_method_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetupIntentConfirmRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "payment_method": obj.get("payment_method"),
            "payment_method_data": PaymentMethodCreateRequest.from_dict(obj["payment_method_data"]) if obj.get("payment_method_data") is not None else None,
            "payment_method_options": obj.get("payment_method_options"),
            "return_url": obj.get("return_url"),
            "use_payjp_sdk": obj.get("use_payjp_sdk")
        })
        return _obj


