# coding: utf-8

"""
    PAY.JP v2 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StatementSubject(str, Enum):
    """
    StatementItemの科目  分類の増減は会計・経理の目線で行われる。 経理上取り扱いが違う数字は別のsubjectになる、もしくはその他の情報を組み合わせて区別できる必要がある。
    """

    """
    allowed enum values
    """
    売上 = '売上'
    決済手数料 = '決済手数料'
    プラットフォーム利用料 = 'プラットフォーム利用料'
    返金 = '返金'
    返金による手数料返還 = '返金による手数料返還'
    返金によるプラットフォーム利用料返還 = '返金によるプラットフォーム利用料返還'
    チャージバック = 'チャージバック'
    チャージバックによる手数料返還 = 'チャージバックによる手数料返還'
    チャージバックによるプラットフォーム利用料返還 = 'チャージバックによるプラットフォーム利用料返還'
    プロプラン利用料 = 'プロプラン利用料'
    有料プラン料金 = '有料プラン料金'
    残高失効 = '残高失効'
    テナント失効金額の割当て = 'テナント失効金額の割当て'
    YELL_BANKお支払い = 'YELL BANKお支払い'
    早期入金サービス利用料 = '早期入金サービス利用料'
    振込手数料 = '振込手数料'
    その他 = 'その他'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatementSubject from a JSON string"""
        return cls(json.loads(json_str))


